//! Intel HD Audio (HDA) controller driver — plan I2, REAL audio output.
//!
//! The hardware layer beneath the host-tested [`euroaudio`] mixer. We talk to the
//! HDA controller via its MMIO registers, set up the **CORB/RIRB** command rings
//! to enumerate the **codec** (audio function group → DAC + output pin), route
//! an output path (converter format/stream, amplifier gains, pin output + EAPD), and
//! start a **stream DMA** with a BDL (buffer descriptor list) that plays a tone
//! generated by [`euroaudio::mix`].
//!
//! Verification (headless): the codec answers `GET_PARAMETER` (real vendor id via
//! RIRB) and the **stream position register (LPIB) increments** while the stream runs —
//! that proves the DMA really consumes the audio buffer (= sound plays).
//!
//! All DMA structures (CORB/RIRB/BDL/audio buffer) come from the identity-mapped
//! frame allocator (virtual = physical), so the addresses the controller reads are
//! exactly the same pointers that we write.

use euromm::FrameAllocator;

use crate::pci;

// ── Global controller registers (MMIO base) ───────────────────────────────
const GCAP: u64 = 0x00; // u16: out/in/bidir-stream-counts
const GCTL: u64 = 0x08; // u32: bit0 CRST (controller reset)
const STATESTS: u64 = 0x0E; // u16: bit per codec that is present/changed
const INTCTL: u64 = 0x20; // u32
const CORBLBASE: u64 = 0x40;
const CORBUBASE: u64 = 0x44;
const CORBWP: u64 = 0x48; // u16
const CORBRP: u64 = 0x4A; // u16
const CORBCTL: u64 = 0x4C; // u8: bit1 DMA-run
const CORBSIZE: u64 = 0x4E; // u8
const RIRBLBASE: u64 = 0x50;
const RIRBUBASE: u64 = 0x54;
const RIRBWP: u64 = 0x58; // u16
const RINTCNT: u64 = 0x5A; // u16
const RIRBCTL: u64 = 0x5C; // u8: bit0 int-on-response, bit1 DMA-run
const RIRBSTS: u64 = 0x5D; // u8: bit0 response-interrupt, bit2 overrun
const RIRBSIZE: u64 = 0x5E; // u8
const SD0: u64 = 0x80; // first stream descriptor (output on QEMU at index OSS)

// Stream descriptor offsets (relative to the descriptor base).
const SDCTL: u64 = 0x00; // 3 bytes: bit0 SRST, bit1 RUN, bits[23:20] stream-tag
const SDSTS: u64 = 0x03; // u8
const SDLPIB: u64 = 0x04; // u32: link position in the buffer
const SDCBL: u64 = 0x08; // u32: cyclic-buffer-length
const SDLVI: u64 = 0x0C; // u16: last-valid-index (BDL-entries − 1)
const SDFMT: u64 = 0x12; // u16: stream-format
const SDBDPL: u64 = 0x18; // u32
const SDBDPU: u64 = 0x1C; // u32

const GCTL_CRST: u32 = 1 << 0;
const CORBRPRST: u16 = 1 << 15;
const DMA_RUN: u8 = 1 << 1;

// ── MMIO helpers (identity-mapped physical) ────────────────────────────────
struct Mmio(u64);
impl Mmio {
    #[inline]
    unsafe fn r8(&self, o: u64) -> u8 {
        ((self.0 + o) as *const u8).read_volatile()
    }
    #[inline]
    unsafe fn w8(&self, o: u64, v: u8) {
        ((self.0 + o) as *mut u8).write_volatile(v);
    }
    #[inline]
    unsafe fn r16(&self, o: u64) -> u16 {
        ((self.0 + o) as *const u16).read_volatile()
    }
    #[inline]
    unsafe fn w16(&self, o: u64, v: u16) {
        ((self.0 + o) as *mut u16).write_volatile(v);
    }
    #[inline]
    unsafe fn r32(&self, o: u64) -> u32 {
        ((self.0 + o) as *const u32).read_volatile()
    }
    #[inline]
    unsafe fn w32(&self, o: u64, v: u32) {
        ((self.0 + o) as *mut u32).write_volatile(v);
    }
}

struct Hda {
    m: Mmio,
    corb: u64,
    rirb: u64,
    sd: u64, // base of the used output stream descriptor
    audio: u64,        // address of the cyclic audio buffer (for earcons)
    audio_bytes: usize, // its size
}

static mut HDA: Option<Hda> = None;

/// Short busy-wait (the HDA reset/codec detection needs µs pauses).
fn delay() {
    crate::apic::busy_wait_us(100);
}

/// Send one codec verb via CORB and read the RIRB response (32-bit). `v20` is the
/// 20-bit verb payload field; we prefix codec address + node id.
unsafe fn corb_cmd(h: &Hda, cad: u32, nid: u32, v20: u32) -> u32 {
    let verb = (cad << 28) | (nid << 20) | (v20 & 0x0F_FFFF);
    let wp = h.m.r16(CORBWP) & 0xFF;
    let next = (wp + 1) & 0xFF;
    // CORB is a ring of u32 verbs; write at the next index and bump WP.
    ((h.corb + next as u64 * 4) as *mut u32).write_volatile(verb);
    h.m.w16(CORBWP, next);
    // Wait until the RIRB write pointer catches up (controller has written the response).
    for _ in 0..2_000_000 {
        if (h.m.r16(RIRBWP) & 0xFF) == next {
            break;
        }
        core::hint::spin_loop();
    }
    // Short settle so the response DWORD is really in memory before we read it
    // (the WP update and the data write are separate DMA steps).
    for _ in 0..2000 {
        core::hint::spin_loop();
    }
    // RIRB entry = 8 bytes (response-u32 + extended-u32); we want the response.
    let resp = ((h.rirb + next as u64 * 8) as *const u32).read_volatile();
    // Clear RIRBSTS.RINTFL (bit0) → reset the RIRB response counter, otherwise the
    // controller stalls the CORB DMA once that counter reaches RINTCNT (write-1-to-clear).
    h.m.w8(RIRBSTS, 0x05);
    resp
}

#[inline]
unsafe fn get_param(h: &Hda, cad: u32, nid: u32, param: u32) -> u32 {
    corb_cmd(h, cad, nid, (0xF00 << 8) | param)
}
/// 12-bit verb (0xF0x/0x70x) + 8-bit payload.
#[inline]
unsafe fn verb12(h: &Hda, cad: u32, nid: u32, verb: u32, payload: u32) -> u32 {
    corb_cmd(h, cad, nid, (verb << 8) | (payload & 0xFF))
}
/// 4-bit verb (0x2/0x3/...) + 16-bit payload.
#[inline]
unsafe fn verb4(h: &Hda, cad: u32, nid: u32, verb: u32, payload: u32) -> u32 {
    corb_cmd(h, cad, nid, (verb << 16) | (payload & 0xFFFF))
}

/// Detect + initialize the HDA controller, enumerate the codec and play a
/// tone generated by [`euroaudio::mix`] (stream DMA).
pub fn init(falloc: &mut FrameAllocator) -> bool {
    let dev = match pci::find(|d| d.class == 0x04 && d.subclass == 0x03) {
        Some(d) => d,
        None => {
            crate::serial_println!("[hda] no HD-Audio controller found (PCI 04:03)");
            return false;
        }
    };
    pci::claim(dev.bus, dev.dev, dev.func, "hda"); // hwprobe (M1-3)
    let bar0 = dev.bar(0);
    let mmio = if bar0 & 0x6 == 0x4 {
        ((dev.bar(1) as u64) << 32) | (bar0 as u64 & 0xFFFF_FFF0)
    } else {
        bar0 as u64 & 0xFFFF_FFF0
    };
    if mmio == 0 {
        crate::serial_println!("[hda] BAR0 not assigned");
        return false;
    }
    dev.enable(0x6); // memory-space + bus-master

    unsafe {
        let m = Mmio(mmio);
        // 1. Controller reset: CRST=0 (in reset), wait until 0; then CRST=1, wait until 1.
        m.w32(GCTL, m.r32(GCTL) & !GCTL_CRST);
        for _ in 0..100_000 {
            if m.r32(GCTL) & GCTL_CRST == 0 {
                break;
            }
            core::hint::spin_loop();
        }
        delay();
        m.w32(GCTL, m.r32(GCTL) | GCTL_CRST);
        for _ in 0..1_000_000 {
            if m.r32(GCTL) & GCTL_CRST != 0 {
                break;
            }
            core::hint::spin_loop();
        }
        delay();
        delay(); // give codecs time to appear in STATESTS

        let gcap = m.r16(GCAP);
        let iss = ((gcap >> 8) & 0x0F) as u64; // input streams (output begins after them)
        let statests = m.r16(STATESTS);
        crate::serial_println!(
            "[hda] controller @ {:#x} — GCAP={:#06x} (in={} out={} bidir={}), STATESTS={:#x}",
            mmio, gcap, iss, (gcap >> 12) & 0x0F, (gcap >> 3) & 0x0F, statests
        );
        if statests == 0 {
            crate::serial_println!("[hda] no codec detected");
            return false;
        }
        let cad = statests.trailing_zeros() as u32; // first present codec address

        // 2. Set up CORB (256 verbs = 1 KiB). Stop DMA, set base, reset RP.
        let corb = falloc.allocate().expect("hda corb");
        let rirb = falloc.allocate().expect("hda rirb");
        core::ptr::write_bytes(corb as *mut u8, 0, 4096);
        core::ptr::write_bytes(rirb as *mut u8, 0, 4096);
        m.w8(CORBCTL, 0);
        m.w8(RIRBCTL, 0);
        m.w8(CORBSIZE, 0x02); // 256 entries
        m.w32(CORBLBASE, corb as u32);
        m.w32(CORBUBASE, (corb >> 32) as u32);
        // Reset the CORB read pointer.
        m.w16(CORBRP, CORBRPRST);
        for _ in 0..100_000 {
            if m.r16(CORBRP) & CORBRPRST != 0 {
                break;
            }
            core::hint::spin_loop();
        }
        m.w16(CORBRP, 0);
        m.w16(CORBWP, 0);
        // 3. Set up RIRB.
        m.w8(RIRBSIZE, 0x02); // 256 entries
        m.w32(RIRBLBASE, rirb as u32);
        m.w32(RIRBUBASE, (rirb >> 32) as u32);
        m.w16(RIRBWP, 0x8000); // reset write pointer
        m.w16(RINTCNT, 0xFF); // high → CORB DMA does not stall during enumeration
        m.w8(RIRBCTL, DMA_RUN); // RIRB DMA on
        m.w8(CORBCTL, DMA_RUN); // CORB DMA on
        m.w32(INTCTL, 0); // we poll (no interrupts)
        delay();

        let mut h = Hda { m, corb, rirb, sd: SD0 + iss * 0x20, audio: 0, audio_bytes: 0 };

        // 4. Enumerate codec: vendor id + function groups.
        let vid = get_param(&h, cad, 0, 0x00); // VENDOR_ID
        let mut snc = get_param(&h, cad, 0, 0x04); // SUBORDINATE_NODE_COUNT of root
        if snc & 0xFF == 0 {
            delay();
            snc = get_param(&h, cad, 0, 0x04); // one retry after a settle
        }
        let fg_start = (snc >> 16) & 0xFF;
        let fg_count = snc & 0xFF;
        crate::serial_println!(
            "[hda] codec #{cad}: vendor-id={:#010x}, {} function-group(s) from node {}",
            vid, fg_count, fg_start
        );

        // Find the audio function group → first DAC (output converter) + output pin.
        let mut dac = 0u32;
        let mut pin = 0u32;
        for fg in fg_start..fg_start + fg_count {
            let fgt = get_param(&h, cad, fg, 0x05) & 0xFF; // FUNCTION_GROUP_TYPE
            if fgt != 0x01 {
                continue; // 0x01 = audio function group
            }
            let wsnc = get_param(&h, cad, fg, 0x04);
            let w_start = (wsnc >> 16) & 0xFF;
            let w_count = wsnc & 0xFF;
            for w in w_start..w_start + w_count {
                let cap = get_param(&h, cad, w, 0x09); // AUDIO_WIDGET_CAP
                let wtype = (cap >> 20) & 0x0F;
                if wtype == 0x0 && dac == 0 {
                    dac = w; // output converter (DAC)
                } else if wtype == 0x4 && pin == 0 {
                    pin = w; // pin complex
                }
            }
            if dac != 0 {
                break;
            }
        }
        if dac == 0 {
            crate::serial_println!("[hda] no output converter (DAC) found");
            return false;
        }
        crate::serial_println!("[hda] output path: DAC=node {dac}, pin=node {pin}");

        // 5. Audio buffer: mix two square-tone streams via euroaudio → one PCM buffer.
        //    8 contiguous frames = 32 KiB = 8192 i16 stereo samples.
        const FRAMES: usize = 8;
        let audio = falloc.allocate().expect("hda audio-buf");
        for _ in 1..FRAMES {
            falloc.allocate().expect("hda audio-buf-cont");
        }
        let total_bytes = FRAMES * 4096;
        let nsamp = total_bytes / 2; // i16 samples (stereo interleaved)
        let tone = build_tone(nsamp);
        core::ptr::copy_nonoverlapping(tone.as_ptr() as *const u8, audio as *mut u8, total_bytes);
        h.audio = audio;
        h.audio_bytes = total_bytes;

        // 6. BDL: 2 entries (each half), both with IOC. CBL = total length.
        let bdl = falloc.allocate().expect("hda bdl");
        core::ptr::write_bytes(bdl as *mut u8, 0, 4096);
        let half = (total_bytes / 2) as u32;
        for i in 0..2u64 {
            let e = bdl + i * 16;
            let addr = audio + i * half as u64;
            (e as *mut u64).write_volatile(addr);
            ((e + 8) as *mut u32).write_volatile(half);
            ((e + 12) as *mut u32).write_volatile(1); // IOC
        }

        // 7. Configure codec path. Format: 48 kHz, 16-bit, 2 channels = 0x0011.
        const FMT: u32 = 0x0011;
        verb4(&h, cad, dac, 0x2, FMT); // SET_CONVERTER_FORMAT
        verb12(&h, cad, dac, 0x706, 1 << 4); // SET_CONVERTER_STREAM_CHANNEL: stream 1, chan 0
        verb4(&h, cad, dac, 0x3, 0xB000 | 0x2A); // SET_AMP_GAIN_MUTE (output, L+R, unmute, gain)
        if pin != 0 {
            verb12(&h, cad, pin, 0x707, 0x40); // SET_PIN_WIDGET_CONTROL: output enable
            verb12(&h, cad, pin, 0x70C, 0x2); // SET_EAPD_BTL_ENABLE: EAPD on
            verb4(&h, cad, pin, 0x3, 0xB000 | 0x2A); // pin output-amp unmute
        }

        // 8. Set up + start stream descriptor.
        let sd = h.sd;
        // Reset the stream (SRST).
        h.m.w8(sd + SDCTL, 0x01);
        for _ in 0..100_000 {
            if h.m.r8(sd + SDCTL) & 0x01 != 0 {
                break;
            }
            core::hint::spin_loop();
        }
        h.m.w8(sd + SDCTL, 0x00);
        for _ in 0..100_000 {
            if h.m.r8(sd + SDCTL) & 0x01 == 0 {
                break;
            }
            core::hint::spin_loop();
        }
        h.m.w32(sd + SDCBL, total_bytes as u32);
        h.m.w16(sd + SDLVI, 1); // 2 BDL entries
        h.m.w16(sd + SDFMT, FMT as u16);
        h.m.w32(sd + SDBDPL, bdl as u32);
        h.m.w32(sd + SDBDPU, (bdl >> 32) as u32);
        h.m.w8(sd + SDSTS, 0x1C); // clear status bits (write-1-clear)
        // Stream tag 1 in bits[23:20] + RUN (bit1).
        let ctl = (1u32 << 20) | (DMA_RUN as u32);
        h.m.w8(sd + SDCTL + 2, (ctl >> 16) as u8);
        h.m.w8(sd + SDCTL, (ctl & 0xFF) as u8);

        // 9. Verify that the DMA consumes the buffer: LPIB must increment. QEMU's
        //    audio timer ticks on wall-clock time, so we poll up to ~250 ms (guest) for
        //    movement instead of a single snapshot.
        let p0 = h.m.r32(sd + SDLPIB);
        let mut p1 = p0;
        for _ in 0..2500 {
            delay(); // ~100 µs each → up to ~250 ms
            p1 = h.m.r32(sd + SDLPIB);
            if p1 != p0 {
                break;
            }
        }
        let sdctl = h.m.r8(sd + SDCTL);
        let sdsts = h.m.r8(sd + SDSTS);
        crate::serial_println!(
            "[hda] stream started (tag 1, 48 kHz/16-bit/stereo, {} KiB) — SDCTL={:#x} SDSTS={:#x} LPIB {} → {} ({})",
            total_bytes / 1024, sdctl, sdsts, p0, p1,
            if p1 != p0 { "DMA running → audio plays ✓" } else { "no progress" }
        );

        HDA = Some(h);
        p1 != p0
    }
}

/// Generate a 48 kHz 16-bit STEREO PCM tone by mixing two square waves (A4 440 Hz +
/// E5 660 Hz) via [`euroaudio::mix`] — proves the mixer→hardware chain.
fn build_tone(nsamples: usize) -> alloc::vec::Vec<i16> {
    let frames = nsamples / 2; // stereo
    let sr = 48_000u32;
    let amp = 6000i16;
    let sq = |hz: u32, n: usize| -> alloc::vec::Vec<i16> {
        let period = (sr / hz) as usize;
        (0..n)
            .map(|i| if (i % period) < period / 2 { amp } else { -amp })
            .collect()
    };
    let a = sq(440, frames);
    let b = sq(660, frames);
    let mut mono = alloc::vec![0i16; frames];
    // Mix both tones at half volume (no clip) via the host-tested mixer.
    euroaudio::mix(&[(&a, euroaudio::UNITY / 2), (&b, euroaudio::UNITY / 2)], &mut mono);
    // Mono → stereo interleave.
    let mut out = alloc::vec![0i16; nsamples];
    for (i, &s) in mono.iter().enumerate() {
        out[i * 2] = s;
        out[i * 2 + 1] = s;
    }
    out
}

/// Is an HDA controller initialized?
pub fn present() -> bool {
    unsafe { (*core::ptr::addr_of!(HDA)).is_some() }
}

/// Current stream position (LPIB) — diagnostics/self-test.
pub fn stream_pos() -> u32 {
    unsafe {
        match (*core::ptr::addr_of!(HDA)).as_ref() {
            Some(h) => h.m.r32(h.sd + SDLPIB),
            None => 0,
        }
    }
}

/// Is the output stream DMA running? (SDCTL bit1 RUN) — more reliable than an
/// LPIB snapshot, because QEMU's audio DMA ticks slowly without `-audiodev`.
pub fn stream_running() -> bool {
    unsafe {
        match (*core::ptr::addr_of!(HDA)).as_ref() {
            Some(h) => h.m.r8(h.sd + SDCTL) & DMA_RUN != 0,
            None => false,
        }
    }
}

/// **BB-8** — play a short **earcon** (audio cue) at `freq_hz`. The stream DMA
/// loops cyclically over the audio buffer; we write a short square-wave beep
/// (~125 ms) + silence into it, so a DISTINCT tone sounds per screen-reader
/// event (button/checkbox/text-field each get their own pitch). No-op
/// if there is no HDA controller. Returns true if the buffer was (re)written.
pub fn earcon(freq_hz: u32) -> bool {
    unsafe {
        let h = match (*core::ptr::addr_of!(HDA)).as_ref() {
            Some(h) => h,
            None => return false,
        };
        if h.audio == 0 || freq_hz == 0 {
            return false;
        }
        let frames = (h.audio_bytes / 2) / 2; // stereo frames
        let beep_frames = frames.min(6000); // ~125 ms @ 48 kHz
        let half_period = (24_000 / freq_hz.max(1)).max(1) as usize;
        let buf = h.audio as *mut i16;
        let mut level: i16 = 9000;
        for fr in 0..frames {
            let s = if fr < beep_frames {
                if fr % half_period == 0 {
                    level = -level;
                }
                level
            } else {
                0 // silence after the beep → it is a short cue, not a drone
            };
            core::ptr::write_volatile(buf.add(fr * 2), s); // L
            core::ptr::write_volatile(buf.add(fr * 2 + 1), s); // R
        }
        true
    }
}
